aws_access_key = "AKIAIQOSPHMZFJ5ZGAPA"
aws_secret_key = "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"
aws_vpc_security_group_ids = "sg-b3e878ce"
aws_key_name = "aws_key-general-tige"
aws_ami = "ami-47e72a3f"
instance_type = "t2.micro"
